using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering.Universal;

// The space the game is played in.
//
// Seven depth layers between the camera and the void, far to near:
//
//   0  deep void      flat theme-tinted black + a gradient of the world's light
//   1  nebula field   baked Blender clouds and a distant galaxy band
//   2  far stars      dust-grade dots, never animated
//   3  cosmic dust    faint speckled patches
//   4  mid stars      the readable ones; only these twinkle
//   5  bright stars   a handful with a flare, kept out of the centre
//   6  asteroid field lit low-poly rocks drifting across the frame
//   7  atmosphere     the world's own colour pooling behind the planet, + vignette
//
// Each layer follows the camera by its own fraction: the void is pinned to the
// camera and never moves, the asteroids follow at 55% and so slide past fastest.
// That difference is the whole parallax — no layer is ever animated upwards, so
// the effect costs one transform write per layer per frame.
//
// Colour comes from SpacePalette, which derives everything from the accent the
// PlanetAmbience registry publishes for the current world. Nothing here knows
// that Natural, Ice or Lava exist.
//
// Nothing in this file is lit, shadowed, post-processed or collidable. The one
// concession to lighting is a 16% tint on the existing Global Light 2D, which is
// what makes the hero planet and the rocket pick up the world's colour.
[DisallowMultipleComponent]
public sealed class SpaceEnvironment : MonoBehaviour
{
    // Which palette entry a renderer takes its colour from.
    enum Slot { Void, VoidGlow, NebulaNear, NebulaFar, Galaxy, Star, Dust, Rock, Atmosphere }

    sealed class Layer
    {
        public Transform root;
        public float follow;                 // 1 = pinned to the camera, 0 = pinned to the world
        public readonly List<Transform> items = new List<Transform>();
    }

    struct Tinted
    {
        public SpriteRenderer renderer;
        public Slot slot;
        public float alpha;                  // at full night, before the day-mode fade
        public float shade;                  // per-instance brightness variation
        public Color current;                // last colour written, twinkle works from this
    }

    struct Twinkle
    {
        public int tint;
        public float period;
        public float offset;
    }

    struct Drifter
    {
        public Transform body;
        public Vector2 velocity;
        public float spin;
    }

    // How much of the world's colour bleeds into the scene light. Above ~0.2 the
    // planets start reading as tinted rather than as lit.
    const float BounceStrength = 0.16f;
    const float ThemeFadeDuration = 1.8f;
    const float ThemePollInterval = 0.4f;

    static SpaceEnvironment instance;

    readonly List<Layer> layers = new List<Layer>(8);
    readonly List<Twinkle> twinkles = new List<Twinkle>(48);
    readonly List<Drifter> drifters = new List<Drifter>(10);
    Tinted[] tints;

    Camera view;
    Light2D globalLight;
    Color globalLightBase;

    float halfWidth;
    float halfHeight;
    float tileHeight;

    string themeName;
    SpacePalette from;
    SpacePalette to;
    float fade = 1f;
    float nextPoll;
    float dayFactor;
    bool paletteDirty = true;
    float activeFadeDuration = ThemeFadeDuration;

    // ─── Installation ────────────────────────────────────────────────────────

    [RuntimeInitializeOnLoadMethod]
    static void Bootstrap() => SceneInstaller.RunOnEveryScene(Install);

    static void Install()
    {
        if (instance != null) return;

        Camera camera = Camera.main;
        if (camera == null) return;

        // Gameplay only. The main menu stages its own backdrop around the hero
        // planet, and the two would fight over the same screen.
        if (camera.GetComponent<CameraFollow>() == null) return;
        if (FindAnyObjectByType<PlanetSpawner>() == null) return;

        RetireLegacyParallax();

        var go = new GameObject("SpaceEnvironment");
        instance = go.AddComponent<SpaceEnvironment>();
    }

    // The old procedural starfield is left in the scene but switched off, so the
    // change is one component toggle away from being reverted. Disabling it
    // before its Start runs is what stops it generating its stars at all.
    static void RetireLegacyParallax()
    {
        ParallaxBackground[] legacy = FindObjectsByType<ParallaxBackground>(FindObjectsInactive.Include);

        for (int i = 0; i < legacy.Length; i++)
        {
            if (legacy[i] == null) continue;
            legacy[i].enabled = false;

            // Stars already generated by an earlier install pass.
            foreach (SpriteRenderer star in legacy[i].GetComponentsInChildren<SpriteRenderer>(true))
                if (star != null) Destroy(star.gameObject);
        }
    }

    // ─── Build ───────────────────────────────────────────────────────────────

    void Awake()
    {
        view = Camera.main;
        if (view == null) { enabled = false; return; }

        halfHeight = view.orthographicSize;
        halfWidth = halfHeight * view.aspect;

        // Tall enough that a wrapped item always re-enters well outside the frame.
        tileHeight = halfHeight * 3.4f;

        globalLight = FindGlobalLight();
        if (globalLight != null) globalLightBase = globalLight.color;

        themeName = CurrentThemeName();
        from = to = SpacePalette.For(themeName);

        var buffer = new List<Tinted>(200);

        BuildVoid(buffer);
        BuildNebulae(buffer);
        BuildFarStars(buffer);
        BuildDust(buffer);
        BuildMidStars(buffer);
        BuildBrightStars(buffer);
        BuildAsteroids(buffer);
        BuildAtmosphere(buffer);

        tints = buffer.ToArray();

        transform.position = new Vector3(0f, view.transform.position.y, 0f);
        SyncLayers();
        RecycleItems();
        ApplyPalette();
    }

    Layer CreateLayer(string name, float follow)
    {
        var go = new GameObject(name);
        go.layer = gameObject.layer;
        go.transform.SetParent(transform, false);

        var layer = new Layer { root = go.transform, follow = follow };
        layers.Add(layer);
        return layer;
    }

    int Add(List<Tinted> buffer, SpriteRenderer renderer, Slot slot, float alpha, float shade = 1f)
    {
        buffer.Add(new Tinted { renderer = renderer, slot = slot, alpha = alpha, shade = shade });
        return buffer.Count - 1;
    }

    // Layer 0 — the sky itself. A flat near-black quad carrying the world's hue,
    // with the world's light pooling towards the bottom of the frame. Pinned to
    // the camera, so it costs two quads for the entire background.
    void BuildVoid(List<Tinted> buffer)
    {
        Layer layer = CreateLayer("Layer0_Void", 1f);

        SpriteRenderer flat = SpaceArt.CreateSprite(layer.root, "DeepVoid", SpaceArt.Flat,
            -200, Vector3.zero, 1f, Color.white);
        SpaceArt.SetWorldSize(flat, halfWidth * 2.4f, halfHeight * 2.4f);
        Add(buffer, flat, Slot.Void, 1f);

        SpriteRenderer gradient = SpaceArt.CreateSprite(layer.root, "VoidGlow", SpaceArt.VoidGradient,
            -199, new Vector3(0f, -halfHeight * 0.42f, 0f), 1f, Color.white);
        SpaceArt.SetWorldSize(gradient, halfWidth * 2.4f, halfHeight * 1.5f);
        Add(buffer, gradient, Slot.VoidGlow, 0.3f);
    }

    // Layer 1 — the deep field. The clouds sit on one diagonal band rather than
    // being scattered, which is what makes them read as a galaxy edge instead of
    // as coloured fog, and the galaxy band itself gives the frame a far horizon.
    void BuildNebulae(List<Tinted> buffer)
    {
        Layer layer = CreateLayer("Layer1_Nebulae", 0.955f);
        Vector2 direction = new Vector2(0.78f, 0.63f).normalized;

        for (int i = 0; i < 9; i++)
        {
            bool wispy = i % 3 == 2;
            float along = Mathf.Lerp(-1.15f, 1.15f, i / 8f) + Random.Range(-0.1f, 0.1f);
            float across = Random.Range(-0.42f, 0.42f);

            var position = new Vector3(
                (direction.x * along - direction.y * across) * halfWidth * 1.7f,
                (direction.y * along + direction.x * across) * tileHeight * 0.5f, 0f);

            SpriteRenderer cloud = SpaceArt.CreateSprite(layer.root, wispy ? "NebulaWisp" : "NebulaSoft",
                wispy ? SpaceArt.NebulaWisp : SpaceArt.NebulaSoft, -190, position,
                Random.Range(halfWidth * 1.6f, halfWidth * 3.1f), Color.white);

            cloud.transform.localRotation = Quaternion.Euler(0f, 0f,
                Mathf.Atan2(direction.y, direction.x) * Mathf.Rad2Deg + Random.Range(-22f, 22f));
            cloud.transform.localScale = new Vector3(
                cloud.transform.localScale.x,
                cloud.transform.localScale.y * Random.Range(0.5f, 0.8f), 1f);

            Add(buffer, cloud, i % 2 == 0 ? Slot.NebulaNear : Slot.NebulaFar,
                wispy ? Random.Range(0.13f, 0.19f) : Random.Range(0.10f, 0.16f));
            layer.items.Add(cloud.transform);
        }

        // Two distant galaxies, well off centre. They are the only warm light in
        // the frame on a cold theme, and the reason the void has a direction.
        for (int i = 0; i < 2; i++)
        {
            var position = new Vector3(
                (i == 0 ? -1f : 1f) * halfWidth * Random.Range(0.5f, 0.85f),
                Random.Range(-tileHeight * 0.45f, tileHeight * 0.45f), 0f);

            SpriteRenderer galaxy = SpaceArt.CreateSprite(layer.root, "GalaxyBand", SpaceArt.GalaxyBand,
                -188, position, Random.Range(halfWidth * 0.85f, halfWidth * 1.25f), Color.white);
            galaxy.transform.localRotation = Quaternion.Euler(0f, 0f, Random.Range(-34f, 34f));

            // Faint on purpose: bright enough to be a landmark, never bright enough
            // to compete with the planet the player is aiming at.
            Add(buffer, galaxy, Slot.Galaxy, Random.Range(0.13f, 0.20f));
            layer.items.Add(galaxy.transform);
        }
    }

    // Layer 2 — star dust. Baked patches rather than individual quads: the same
    // hundred-odd stars for six draw calls instead of fifty. Three variants,
    // randomly rotated and mirrored, so the repeat never becomes visible.
    void BuildFarStars(List<Tinted> buffer)
    {
        Layer layer = CreateLayer("Layer2_FarStars", 0.925f);
        Sprite[] fields = SpaceArt.StarFields;

        for (int i = 0; i < 6; i++)
        {
            float size = Random.Range(halfWidth * 1.5f, halfWidth * 2.4f);

            SpriteRenderer patch = SpaceArt.CreateSprite(layer.root, "StarField",
                fields[i % fields.Length], -182, RandomInTile(0.85f), size, Color.white);

            patch.transform.localRotation = Quaternion.Euler(0f, 0f, Random.Range(0f, 360f));
            if (Random.value < 0.5f)
            {
                Vector3 scale = patch.transform.localScale;
                scale.x = -scale.x;
                patch.transform.localScale = scale;
            }

            Add(buffer, patch, Slot.Star, Random.Range(0.55f, 0.85f), Random.Range(0.8f, 1f));
            layer.items.Add(patch.transform);
        }
    }

    // Layer 3 — cosmic dust. Baked speckle patches, faint enough to be felt rather
    // than seen; they are what stops the gaps between stars reading as empty.
    void BuildDust(List<Tinted> buffer)
    {
        Layer layer = CreateLayer("Layer3_Dust", 0.885f);

        for (int i = 0; i < 5; i++)
        {
            SpriteRenderer patch = SpaceArt.CreateSprite(layer.root, "DustPatch", SpaceArt.DustPatch, -178,
                RandomInTile(0.95f), Random.Range(halfWidth * 0.9f, halfWidth * 1.8f), Color.white);
            patch.transform.localRotation = Quaternion.Euler(0f, 0f, Random.Range(0f, 360f));

            Add(buffer, patch, Slot.Dust, Random.Range(0.10f, 0.18f));
            layer.items.Add(patch.transform);
        }
    }

    // Layer 4 — the readable stars. Only these twinkle, which is what sells the
    // depth: a starfield where everything blinks reads as noise.
    void BuildMidStars(List<Tinted> buffer)
    {
        Layer layer = CreateLayer("Layer4_MidStars", 0.80f);

        for (int i = 0; i < 24; i++)
        {
            SpriteRenderer star = SpaceArt.CreateSprite(layer.root, "MidStar", SpaceArt.Dot, -172,
                RandomInTile(1.08f), halfHeight * Random.Range(0.009f, 0.017f), Color.white);

            int index = Add(buffer, star, Slot.Star, Random.Range(0.55f, 0.92f), Random.Range(0.82f, 1f));
            twinkles.Add(new Twinkle { tint = index, period = Random.Range(2f, 5.4f), offset = Random.Range(0f, 10f) });
            layer.items.Add(star.transform);
        }
    }

    // Layer 5 — landmark stars with a soft flare, pushed away from the middle of
    // the frame so nothing bright ever sits next to the hero planet.
    void BuildBrightStars(List<Tinted> buffer)
    {
        Layer layer = CreateLayer("Layer5_BrightStars", 0.70f);

        for (int i = 0; i < 7; i++)
        {
            var position = new Vector3(
                Random.Range(0.5f, 1.05f) * halfWidth * (Random.value < 0.5f ? -1f : 1f),
                Random.Range(-tileHeight * 0.5f, tileHeight * 0.5f), 0f);

            SpriteRenderer star = SpaceArt.CreateSprite(layer.root, "BrightStar", SpaceArt.StarFlare, -166,
                position, halfHeight * Random.Range(0.045f, 0.085f), Color.white);

            int index = Add(buffer, star, Slot.Star, Random.Range(0.5f, 0.75f));
            twinkles.Add(new Twinkle { tint = index, period = Random.Range(3.6f, 7.4f), offset = Random.Range(0f, 10f) });
            layer.items.Add(star.transform);
        }
    }

    // Layer 6 — the asteroid field. Three baked clusters carry the density and six
    // single rocks carry the motion, so a whole field costs nine quads and nine
    // transform writes. Recycled in place: no spawning, no particle system.
    void BuildAsteroids(List<Tinted> buffer)
    {
        Layer layer = CreateLayer("Layer6_Asteroids", 0.55f);
        Sprite[] rocks = SpaceArt.Rocks;

        // Small and dark. Blown up large and half-transparent the cluster stops
        // reading as distant rock and starts reading as broken glass over the frame.
        for (int i = 0; i < 4; i++)
        {
            SpriteRenderer cluster = SpaceArt.CreateSprite(layer.root, "RockCluster", SpaceArt.RockCluster, -160,
                RandomInTile(0.9f), Random.Range(halfWidth * 0.26f, halfWidth * 0.44f), Color.white);
            cluster.transform.localRotation = Quaternion.Euler(0f, 0f, Random.Range(0f, 360f));

            Add(buffer, cluster, Slot.Rock, Random.Range(0.34f, 0.5f), Random.Range(0.32f, 0.5f));
            layer.items.Add(cluster.transform);
            drifters.Add(new Drifter
            {
                body = cluster.transform,
                velocity = new Vector2(Random.Range(-0.06f, -0.015f), 0f),
                spin = Random.Range(-1.6f, 1.6f)
            });
        }

        for (int i = 0; i < 6; i++)
        {
            SpriteRenderer rock = SpaceArt.CreateSprite(layer.root, "Rock", rocks[i % rocks.Length], -159,
                RandomInTile(1.0f), Random.Range(halfWidth * 0.05f, halfWidth * 0.13f), Color.white);
            rock.transform.localRotation = Quaternion.Euler(0f, 0f, Random.Range(0f, 360f));

            Add(buffer, rock, Slot.Rock, Random.Range(0.4f, 0.62f), Random.Range(0.45f, 0.75f));
            layer.items.Add(rock.transform);
            drifters.Add(new Drifter
            {
                body = rock.transform,
                velocity = new Vector2(Random.Range(-0.11f, -0.03f), Random.Range(-0.03f, 0.03f)),
                spin = Random.Range(-6f, 6f)
            });
        }
    }

    // Layer 7 — the world's own light in the void, and the vignette that pulls the
    // corners down. Both are pinned to the camera and sit behind every planet, so
    // the hero planet is always the brightest thing in the frame.
    void BuildAtmosphere(List<Tinted> buffer)
    {
        Layer layer = CreateLayer("Layer7_Atmosphere", 1f);

        // Both are deliberately faint. An atmosphere you can see as a shape is a
        // green (or blue, or orange) fog sitting over the whole frame; an
        // atmosphere at 2-3% is the world's colour being *felt* in the void.
        SpriteRenderer wide = SpaceArt.CreateSprite(layer.root, "AtmosphereWide", SpaceArt.Dot, -150,
            new Vector3(0f, -halfHeight * 0.15f, 0f), halfWidth * 2.6f, Color.white);
        Add(buffer, wide, Slot.Atmosphere, 0.022f);

        SpriteRenderer core = SpaceArt.CreateSprite(layer.root, "AtmosphereCore", SpaceArt.Dot, -149,
            Vector3.zero, halfWidth * 1.3f, Color.white);
        Add(buffer, core, Slot.Atmosphere, 0.03f);

        SpriteRenderer vignette = SpaceArt.CreateSprite(layer.root, "Vignette", SpaceArt.Vignette, -146,
            Vector3.zero, 1f, new Color(0f, 0f, 0f, 0.6f));
        SpaceArt.SetWorldSize(vignette, halfWidth * 2.2f, halfHeight * 2.2f);
        // Black, so it takes no palette slot; only the day fade touches it.
        Add(buffer, vignette, Slot.Void, 0.6f, 0f);
    }

    // Only the scene's global light is tinted. A spot or freeform light belongs to
    // an effect, and re-colouring it would change what that effect looks like.
    static Light2D FindGlobalLight()
    {
        Light2D[] lights = FindObjectsByType<Light2D>();
        for (int i = 0; i < lights.Length; i++)
            if (lights[i] != null && lights[i].lightType == Light2D.LightType.Global) return lights[i];

        return null;
    }

    Vector3 RandomInTile(float widthFactor)
    {
        return new Vector3(
            Random.Range(-halfWidth, halfWidth) * widthFactor,
            Random.Range(-tileHeight * 0.5f, tileHeight * 0.5f), 0f);
    }

    // ─── Per frame ───────────────────────────────────────────────────────────

    // How present the world's sky is, 0–1. The main menu frames the hero planet
    // against its own staged void, so the game sky is held at zero while the menu is
    // up and rises back to one as the camera pulls out into the game. Kept as a
    // multiplier rather than a renderer toggle so the layers never stop tracking the
    // camera, and so the twinkles inherit it for free through tint.current.
    public static float PresentationAlpha = 1f;

    float appliedPresentationAlpha = 1f;

    void LateUpdate()
    {
        if (view == null) return;

        // While the main menu showcase is up it parks the game camera's culling
        // mask at zero and stages its own backdrop on another layer. None of this
        // is on screen then, so none of it should cost anything.
        if (view.cullingMask == 0) return;

        if (!Mathf.Approximately(appliedPresentationAlpha, PresentationAlpha))
        {
            appliedPresentationAlpha = PresentationAlpha;
            paletteDirty = true;
        }

        SyncLayers();
        RecycleItems();
        DriftAsteroids();
        PollTheme();
        AdvanceFade();

        if (paletteDirty) ApplyPalette();

        AnimateTwinkles();
    }

    void SyncLayers()
    {
        Vector3 camera = view.transform.position;

        for (int i = 0; i < layers.Count; i++)
        {
            Layer layer = layers[i];
            if (layer.root == null) continue;
            layer.root.position = new Vector3(camera.x * layer.follow, camera.y * layer.follow, 0f);
        }
    }

    // Wraps every item into a band one tile tall that starts just below the
    // screen. Cheaper than sorting or pooling, and stable however far the rocket
    // has climbed.
    void RecycleItems()
    {
        float lower = view.transform.position.y - halfHeight - halfHeight * 0.35f;
        float upper = lower + tileHeight;

        for (int i = 0; i < layers.Count; i++)
        {
            Layer layer = layers[i];
            if (layer.follow >= 1f || layer.root == null) continue;

            float rootY = layer.root.position.y;
            List<Transform> items = layer.items;

            for (int j = 0; j < items.Count; j++)
            {
                Transform item = items[j];
                if (item == null) continue;

                float world = rootY + item.localPosition.y;
                if (world < lower) item.localPosition += new Vector3(0f, tileHeight, 0f);
                else if (world > upper) item.localPosition -= new Vector3(0f, tileHeight, 0f);
            }
        }
    }

    void DriftAsteroids()
    {
        float delta = Time.unscaledDeltaTime;
        float bound = halfWidth * 1.4f;

        for (int i = 0; i < drifters.Count; i++)
        {
            Drifter drifter = drifters[i];
            if (drifter.body == null) continue;

            Vector3 position = drifter.body.localPosition;
            position.x += drifter.velocity.x * delta;
            position.y += drifter.velocity.y * delta;
            if (position.x < -bound) position.x = bound;

            drifter.body.localPosition = position;
            drifter.body.Rotate(0f, 0f, drifter.spin * delta);
        }
    }

    void AnimateTwinkles()
    {
        if (tints == null) return;
        float time = Time.unscaledTime;

        for (int i = 0; i < twinkles.Count; i++)
        {
            Twinkle twinkle = twinkles[i];
            Tinted tint = tints[twinkle.tint];
            if (tint.renderer == null) continue;

            float wave = (Mathf.Sin((time + twinkle.offset) * (Mathf.PI * 2f / twinkle.period)) + 1f) * 0.5f;
            Color color = tint.current;
            color.a *= Mathf.Lerp(0.4f, 1f, wave);
            tint.renderer.color = color;
        }
    }

    // ─── Theme ───────────────────────────────────────────────────────────────

    void PollTheme()
    {
        bool day = DayNightManager.instance != null && DayNightManager.instance.IsDayMode();
        float targetDay = day ? 1f : 0f;
        if (!Mathf.Approximately(dayFactor, targetDay))
        {
            dayFactor = Mathf.MoveTowards(dayFactor, targetDay, Time.unscaledDeltaTime * 1.6f);
            paletteDirty = true;
        }

        if (Time.unscaledTime < nextPoll) return;
        nextPoll = Time.unscaledTime + ThemePollInterval;

        string current = CurrentThemeName();
        if (current == themeName) return;

        // Start the cross-fade from wherever the last one got to, so worlds
        // changed in quick succession never snap.
        from = fade >= 1f ? to : SpacePalette.Lerp(from, to, fade);
        to = SpacePalette.For(current);
        themeName = current;
        fade = 0f;
        paletteDirty = true;
    }

    void AdvanceFade()
    {
        if (fade >= 1f)
        {
            activeFadeDuration = ThemeFadeDuration;
            return;
        }

        fade = Mathf.Min(1f, fade + Time.unscaledDeltaTime / activeFadeDuration);
        paletteDirty = true;
    }

    static string CurrentThemeName()
    {
        int score = GameManager.instance != null ? GameManager.instance.GetScore() : 0;
        int index = PlanetSpawner.LevelIndexForScore(score);

        string[] names = PlanetSpawner.LevelNames;
        return names != null && index >= 0 && index < names.Length ? names[index] : null;
    }

    public static void CrossfadeToTheme(string themeName, float duration)
    {
        if (instance == null || string.IsNullOrEmpty(themeName)) return;

        instance.from = instance.fade >= 1f ? instance.to : SpacePalette.Lerp(instance.from, instance.to, instance.fade);
        instance.to = SpacePalette.For(themeName);
        instance.themeName = themeName;
        instance.fade = 0f;
        instance.activeFadeDuration = Mathf.Max(0.05f, duration);
        instance.paletteDirty = true;
        instance.nextPoll = Time.unscaledTime + ThemePollInterval;
    }

    void ApplyPalette()
    {
        paletteDirty = false;
        if (tints == null) return;

        SpacePalette palette = fade >= 1f ? to : SpacePalette.Lerp(from, to, Mathf.SmoothStep(0f, 1f, fade));

        for (int i = 0; i < tints.Length; i++)
        {
            Tinted tint = tints[i];
            if (tint.renderer == null) continue;

            Color color = ColourFor(tint.slot, palette);
            color.r *= tint.shade;
            color.g *= tint.shade;
            color.b *= tint.shade;
            color.a = tint.alpha * DayFade(tint.slot) * Mathf.Clamp01(PresentationAlpha);

            tint.current = color;
            tints[i] = tint;
            tint.renderer.color = color;
        }

        if (globalLight != null)
        {
            // Day mode already lifts the whole scene, so the world's colour is
            // pulled back rather than stacked on top of it.
            float strength = BounceStrength * (1f - 0.5f * dayFactor);
            globalLight.color = Color.Lerp(globalLightBase, palette.bounce, strength);
        }
    }

    static Color ColourFor(Slot slot, SpacePalette palette)
    {
        switch (slot)
        {
            case Slot.Void: return palette.deepVoid;
            case Slot.VoidGlow: return palette.voidGlow;
            case Slot.NebulaNear: return palette.nebulaNear;
            case Slot.NebulaFar: return palette.nebulaFar;
            case Slot.Galaxy: return palette.galaxy;
            case Slot.Star: return palette.star;
            case Slot.Dust: return palette.dust;
            case Slot.Rock: return palette.rock;
            default: return palette.atmosphere;
        }
    }

    // Day mode turns the sky pale: the void has to get out of the way of the
    // camera's own clear colour, and everything else steps back rather than
    // disappearing, so the layers are still there when night returns.
    float DayFade(Slot slot)
    {
        switch (slot)
        {
            case Slot.Void:
            case Slot.VoidGlow: return 1f - dayFactor;
            case Slot.NebulaNear:
            case Slot.NebulaFar:
            case Slot.Galaxy: return 1f - 0.75f * dayFactor;
            case Slot.Atmosphere: return 1f - 0.6f * dayFactor;
            default: return 1f - 0.55f * dayFactor;
        }
    }
}
